name: Force Merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create GitHub App Token
      id: create_token
      uses: actions/create-github-app-token@v1.11.5
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Comment on the pull request
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "This PR will be force merged."
      env:
        GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}

    - name: Merge the pull request
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }} --delete-branch 
      env:
        GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}