name: Java CI with Maven

on:
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3.1.0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3.5.1
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -f sandbox-maven/pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -f sandbox-maven/pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
