name: Java CI with Maven

on:
  push:
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PACKAGE_PATTERN: 'sandbox-maven-*.jar'

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3.5.1
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -f sandbox-maven/pom.xml

    - name: Get Package Path
      id: get_package
      run: | 
        echo "::set-output name=package_path::$(find . -name $PACKAGE_PATTERN)"
        echo "::set-output name=package_name::$(find . -name $PACKAGE_PATTERN -printf "%f\n")"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ steps.get_package.outputs.package_name }}
        path: ${{ steps.get_package.outputs.package_path }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -f sandbox-maven/pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
